config/routes.rb
Treebook::Application.routes.draw do
  resources :statuses

  resources :staatus

end

app/models/staatu.rb
class Staatu < ActiveRecord::Base
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/staatus_controller.rb
class StaatusController < ApplicationController
  # GET /staatus
  # GET /staatus.json
  def index
    @staatus = Staatu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @staatus }
    end
  end

  # GET /staatus/1
  # GET /staatus/1.json
  def show
    @staatu = Staatu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @staatu }
    end
  end

  # GET /staatus/new
  # GET /staatus/new.json
  def new
    @staatu = Staatu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @staatu }
    end
  end

  # GET /staatus/1/edit
  def edit
    @staatu = Staatu.find(params[:id])
  end

  # POST /staatus
  # POST /staatus.json
  def create
    @staatu = Staatu.new(params[:staatu])

    respond_to do |format|
      if @staatu.save
        format.html { redirect_to @staatu, notice: 'Staatu was successfully created.' }
        format.json { render json: @staatu, status: :created, location: @staatu }
      else
        format.html { render action: "new" }
        format.json { render json: @staatu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /staatus/1
  # PUT /staatus/1.json
  def update
    @staatu = Staatu.find(params[:id])

    respond_to do |format|
      if @staatu.update_attributes(params[:staatu])
        format.html { redirect_to @staatu, notice: 'Staatu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @staatu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staatus/1
  # DELETE /staatus/1.json
  def destroy
    @staatu = Staatu.find(params[:id])
    @staatu.destroy

    respond_to do |format|
      format.html { redirect_to staatus_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/staatus_helper.rb
module StaatusHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/staatus/_form.html.erb
<%= form_for(@staatu) do |f| %>
  <% if @staatu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staatu.errors.count, "error") %> prohibited this staatu from being saved:</h2>

      <ul>
      <% @staatu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/staatus/edit.html.erb
<h1>Editing staatu</h1>

<%= render 'form' %>

<%= link_to 'Show', @staatu %> |
<%= link_to 'Back', staatus_path %>

app/views/staatus/index.html.erb
<h1>Listing staatus</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @staatus.each do |staatu| %>
  <tr>
    <td><%= staatu.name %></td>
    <td><%= staatu.content %></td>
    <td><%= link_to 'Show', staatu %></td>
    <td><%= link_to 'Edit', edit_staatu_path(staatu) %></td>
    <td><%= link_to 'Destroy', staatu, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Staatu', new_staatu_path %>

app/views/staatus/new.html.erb
<h1>New staatu</h1>

<%= render 'form' %>

<%= link_to 'Back', staatus_path %>

app/views/staatus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @staatu.name %>
</p>

<p>
  <b>Content:</b>
  <%= @staatu.content %>
</p>


<%= link_to 'Edit', edit_staatu_path(@staatu) %> |
<%= link_to 'Back', staatus_path %>

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<h1>Listing statuses</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @statuses.each do |status| %>
  <tr>
    <td><%= status.name %></td>
    <td><%= status.content %></td>
    <td><%= link_to 'Show', status %></td>
    <td><%= link_to 'Edit', edit_status_path(status) %></td>
    <td><%= link_to 'Destroy', status, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @status.name %>
</p>

<p>
  <b>Content:</b>
  <%= @status.content %>
</p>


<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>